### ISSUE TITLE
Generalization of the hierarchy

### ISSUE THREAD

**Issue by BradKML** [stitchfix/colornamer#1]
There are other places that include a wider set of colors.
https://github.com/meodai/color-names and https://github.com/colorjs/color-namer being the biggest.
Would it be applicable to expand further to other places? (CSS, Windows, Professionally Curated Sources)

**Comment by dantasse** [comment]
Hey @BrandonKMLee! Sorry I never noticed this. I know what you mean, everyone's got their own list of colors. We're not trying to say that ours is the only one, or to unite all the lists; we're just providing one more.

(why add one more then? well, ours is hierarchical - so if you know something is xkcd color `adobe`, you know it's also design color `russet brown` and common color `sienna` (more description [here](https://multithreaded.stitchfix.com/blog/2020/09/02/what-color-is-this/). This has been helpful to us, hopefully it's helpful to others too.)
